export enum Category {
  PRODUCTS = "Продукты",
  ENTERTAINMENT = "Развлечения",
  TRANSPORT = "Транспорт",
  HEALTH = "Здоровье",
  HOME = "ЖКХ",
  EDUCATION = "Обучение",
  FITNESS = "Фитнес",
  TAXES = "Налоги",
  SALARY = "Зарплата",
  REWARD = "Награда",
  PRESENT = "Подарок",
  SALES = "Продажа",
  OTHER = "Другое",
}
